#!/bin/bash
echo "Nhập vào số n:"
read n
while [ $n -lt 10 ]
do
    echo "Hãy nhập lại(n phải lớn hơn 10):"
    read n
done

sum=0;
for ((i=1;i<=n;i++))
do
    sum=$((sum+i))
done

echo "Tổng của n số hạng là: $sum"